apiVersion: v1
kind: Service
metadata:
  namespace: myapps
  name: app1-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: app1